In [3]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np
import pandas as pd

plt.style.use("fivethirtyeight")

In [2]:
!pip install joblib

  Using cached joblib-1.2.0-py3-none-any.whl (297 kB)


In [4]:
np.random.randn(3)

array([-1.04837876,  0.55155489, -0.92592346])

In [5]:
1e-4

0.0001

In [6]:
X = -np.ones((4,2))

In [16]:
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [7]:
np.c_[X, -np.ones((len(X),1))]

array([[-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.]])

In [12]:
class Perceptron:
    def __init__(self, eta:float=None,epochs:int = None):  ##eta is the learning-rate
        self.weights = np.random.randn(3) * 1e-4 #randn Returns a samples from the "standard normal" distribution. 
                                                 # weights should be minimal to reduce the weight updation
        self.eta = eta ##
        self.epochs =epochs ## iterations
        
    def _z_outcome(self,inputs,weights):
        return np.dot(inputs,weights)  #multip,ication of weights and the input values
    
    def activation_function(self,z):
        return np.where(z>0,1,0)
        
    def fit(self,X,y):
        self.X= X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]  ## bias weights multiplication
        print(f"X with bias:\n{X_with_bias}")
        
        
        for epoch in range(self.epochs):
            print("--"*10)  # To seperate and print the outcomes
            print(f"for epochs>> {epoch+1}") ## will print the no of epochs everytime
            print("--"*10)
            
            z = self._z_outcome(X_with_bias,self.weights) ## for activation function
            y_hat = self.activation_function(z)   ## y_hat is our predicted output
            print(f"Predicted value after the forward pass: \{y_hat}")
            
            self.error = self.y - y_hat  ## for error between predicted and the actual values
            print(f"error:\n{self.error}")
            
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T,self.error) ## weight updation
            print(f"updated weights after the epochs: {epoch + 1}/{self.epochs}:\n{self.weights}")
            print(f"##"*10)
            
    def predict(self,X):
        X_with_bias = np.c_[X, -np.ones((len(X),1))]
        z = self._z_outcome(X_with_bias,self.weights)
        return self.activation_function(z)
    
            
            
            
        
            

In [13]:
## This is OR Gate table

OR = {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y"  : [0,1,1,1]
}

df_OR = pd.DataFrame(OR)  ## putting into the dataframe
df_OR





x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [17]:
# This is AND Gate table

AND = {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y"  : [0,0,0,1]
}

df_AND = pd.DataFrame(AND)  ## putting into the Dataframe
df_AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [35]:
# This is XOR Gate table

XOR = {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y"  : [0,1,1,0]
}

df_XOR = pd.DataFrame(XOR)  ## putting into the Dataframe
df_XOR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0

In [56]:
# This is NAND Gate table

NAND = {
    "x1" : [0,0,1,1],
    "x2" : [0,1,0,1],
    "y"  : [1,0,0,0]
}

df_NAND = pd.DataFrame(NAND)  ## putting into the Dataframe
df_NAND

x1  x2  y
0   0   0  1
1   0   1  0
2   1   0  0
3   1   1  0

In [36]:
def prepare_data(df, target_col = "y"):
    X = df.drop(target_col, axis=1)
    y = df[target_col]
    
    return X,y

In [37]:
## Prediction for the OR Gate

X,y = prepare_data(df_OR)

ETA = 0.1
EPOCHS = 10

model_or = Perceptron(eta = ETA ,epochs=EPOCHS )

## fitting the model
model_or.fit(X,y)


X with bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epochs>> 1
--------------------
Predicted value after the forward pass: \[0 1 0 1]
error:
0    0
1    0
2    1
3    0
Name: y, dtype: int64
updated weights after the epochs: 1/10:
[ 0.10004091  0.0001363  -0.09987291]
####################
--------------------
for epochs>> 2
--------------------
Predicted value after the forward pass: \[1 1 1 1]
error:
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after the epochs: 2/10:
[0.10004091 0.0001363  0.00012709]
####################
--------------------
for epochs>> 3
--------------------
Predicted value after the forward pass: \[0 1 1 1]
error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after the epochs: 3/10:
[0.10004091 0.0001363  0.00012709]
####################
--------------------
for epochs>> 4
--------------------
Predicted value after the forward pass: \[0 1 1 1]
error:
0    0
1    0
2    0
3   

In [38]:
model_or.predict(X)

array([0, 1, 1, 1])

In [39]:
## Prediction for the AND Gate

X,y = prepare_data(df_AND)

ETA = 0.1
EPOCHS = 10

model_and = Perceptron(eta = ETA ,epochs=EPOCHS )

## fitting the model
model_and.fit(X,y)


X with bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epochs>> 1
--------------------
Predicted value after the forward pass: \[0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after the epochs: 1/10:
[ 0.09999113  0.09992424 -0.09999315]
####################
--------------------
for epochs>> 2
--------------------
Predicted value after the forward pass: \[1 1 1 1]
error:
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights after the epochs: 2/10:
[-8.86677672e-06 -7.57551783e-05  2.00006848e-01]
####################
--------------------
for epochs>> 3
--------------------
Predicted value after the forward pass: \[0 0 0 0]
error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after the epochs: 3/10:
[0.09999113 0.09992424 0.10000685]
####################
--------------------
for epochs>> 4
--------------------
Predicted value after the forward pass: \[0 0 0 1]
error:
0    0
1  

In [40]:
model_and.predict(X)

array([0, 0, 0, 1])

In [44]:
## Prediction for the XOR Gate

X,y = prepare_data(df_XOR)

ETA = 0.1
EPOCHS = 10

model_xor = Perceptron(eta = ETA ,epochs=EPOCHS )

## fitting the model
model_xor.fit(X,y)


X with bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epochs>> 1
--------------------
Predicted value after the forward pass: \[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights after the epochs: 1/10:
[ 0.09996758  0.10007235 -0.19987897]
####################
--------------------
for epochs>> 2
--------------------
Predicted value after the forward pass: \[1 1 1 1]
error:
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights after the epochs: 2/10:
[-3.24245483e-05  7.23527487e-05  1.21027061e-04]
####################
--------------------
for epochs>> 3
--------------------
Predicted value after the forward pass: \[0 0 0 0]
error:
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights after the epochs: 3/10:
[ 0.09996758  0.10007235 -0.19987897]
####################
--------------------
for epochs>> 4
--------------------
Predicted value after the forward pass: \[1 1 1 1]
error:
0   -1


In [59]:
### Perceptron is only sutaible for linearly seperable datasets.(OR,AND,NAND)

## So for XOR gate it will predict wrong output for any number of epochs as they are not linearly seperable

In [60]:
model_xor.predict(X)  ## It will predict wrong answer

array([0, 0, 0, 0])

In [57]:
## Prediction for the NAND Gate

X,y = prepare_data(df_NAND)

ETA = 0.1
EPOCHS = 10

model_nand = Perceptron(eta = ETA ,epochs=EPOCHS )

## fitting the model
model_nand.fit(X,y)

X with bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epochs>> 1
--------------------
Predicted value after the forward pass: \[1 1 1 1]
error:
0    0
1   -1
2   -1
3   -1
Name: y, dtype: int64
updated weights after the epochs: 1/10:
[-0.20012137 -0.1999932   0.29984009]
####################
--------------------
for epochs>> 2
--------------------
Predicted value after the forward pass: \[0 0 0 0]
error:
0    1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after the epochs: 2/10:
[-0.20012137 -0.1999932   0.19984009]
####################
--------------------
for epochs>> 3
--------------------
Predicted value after the forward pass: \[0 0 0 0]
error:
0    1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after the epochs: 3/10:
[-0.20012137 -0.1999932   0.09984009]
####################
--------------------
for epochs>> 4
--------------------
Predicted value after the forward pass: \[0 0 0 0]
error:
0    1
1    0
2    

In [58]:
model_nand.predict(X)

array([1, 0, 0, 0])

In [46]:

X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [47]:
y

0    0
1    1
2    1
3    0
Name: y, dtype: int64

In [48]:
obj  =Perceptron(eta=0.01,epochs=10)

In [49]:
obj.eta

0.01

In [50]:
obj.epochs

10

In [51]:
obj.weights


array([ 2.72488738e-05,  1.09102649e-04, -1.19291239e-04])

In [52]:
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [53]:
y =np.ones((4,1))
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [54]:
obj.fit(X,y)

X with bias:
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epochs>> 1
--------------------
Predicted value after the forward pass: \[1 1 1 1]
error:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


ValueError: operands could not be broadcast together with shapes (3,) (3,4) 

In [ ]:
z=-23
np.where(z>0,1,0)