In [3]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np

plt.style.use("fivethirtyeight")

In [2]:
!pip install joblib

  Using cached joblib-1.2.0-py3-none-any.whl (297 kB)


In [8]:
np.random.randn(3)

array([-0.0109694 , -0.28162108, -0.81097362])

In [9]:
1e-4

0.0001

In [14]:
X = -np.ones((4,2))

In [17]:
np.c_[X, -np.ones((len(X),1))]

array([[-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.],
       [-1., -1., -1.]])

In [22]:
class Perceptron:
    def __init__(self, eta:float=None,epochs:int = None):  ##eta is the learning-rate
        self.weights = np.random.randn(3) * 1e-4 #randn Returns a samples from the "standard normal" distribution. 
                                                 # weights should be minimal to reduce the weight updation
        self.eta = eta ##
        self.epochs =epochs ## iterations
        
    def _z_outcome(self,inputs,weights):
        return np.dot(inputs,weights)  #multip,ication of weights and the input values
    
    def activation_function(self,z):
        return np.where(z>0,1,0)
        
    def fit(self,X,y):
        self.X= X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]  ## bias weights multiplication
        print(f"X with bias:\n{X_with_bias}")
        
        
        for epochs in range(self.epochs):
            z = self._z_outcome(X_with_bias,self.weights) ## for activation function
            y_hat = self.activation_function(z) 
            
            self.error = self.y - y_hat  ## for error between predicted and the actual values
            
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T,self.error) ## weight updation
            
    def predict(self,X):
        X_with_bias = np.c_[X, -np.ones((len(X),1))]
        z = self._z_outcome(X_with_bias,self.weights)
        return self.activation_function(z)
    
            
            
            
        
            

In [24]:
obj  =Perceptron(eta=0.01,epochs=10)

In [25]:
obj.eta

0.01

In [26]:
obj.epochs

10

In [27]:
obj.weights


array([ 4.82465348e-05, -7.21149087e-05,  1.18183552e-04])

In [28]:
X

array([[-1., -1.],
       [-1., -1.],
       [-1., -1.],
       [-1., -1.]])

In [31]:
y =np.ones((4,1))
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [32]:
obj.fit(X,y)

X with bias:
[[-1. -1. -1.]
 [-1. -1. -1.]
 [-1. -1. -1.]
 [-1. -1. -1.]]


In [34]:
z=-23
np.where(z>0,1,0)

array(0)